<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MAUIDesigner.Fresh.Core\MAUIDesigner.Fresh.Core.csproj" />
    <ProjectReference Include="..\MAUIDesigner.Ddp\MAUIDesigner.Ddp.csproj" />
  </ItemGroup>

</Project>
